### ISSUE TITLE
Spike de formas de instalación de CKAN de acuerdo al entorno

### ISSUE THREAD

**Issue by pilimayora** [transparencia-argentina/ckan#1]
Output:

Documento en el Drive de transparencia/ckan con ventajas y desventajas de cada entorno. Debe incluir proceso de instalación de cada entorno.

**Comment by plorenzatto** [comment]
Doc del spike:
https://docs.google.com/document/d/1fWHyAF5glAXMqKqH402KDqRO-l5E2Kl0xl_f9K75iVA/edit
