### ISSUE TITLE
Correcciones Vista Landing de portal V0

### ISSUE THREAD

**Issue by pilimayora** [transparencia-argentina/ckan#27]
Correcciones:
-Agregar botón “Datos”
-Darle “una vuelta” al background del landing.
-Mayor presencia del buscador.
-Secciones quedan Datos, organizaciones.
-Favicon (icon de casa rosada)
-Box de contenido a definir.
-Acerca del sitio va en el footer junto a las redes sociales.
-Grupos cambian Nati lo manda x mail.
	
Contenido: Titulo y bajada

**Comment by mechafiz** [comment]
Estado: UX-UI
