### ISSUE TITLE
Wireframe Vista Datos V0

### ISSUE THREAD

**Issue by pilimayora** [transparencia-argentina/ckan#28]
-Nacho va a hacer research a ver si es posible un filtrado dinámico tipo ciudad.
-Según eso se define si: Filtro dinámico va en V0 o V1
	Contenido:
	Filtros: Grupos - Organizaciones - Tags // Formatos - Licencia (v1)
	Ordenar por: últimos publicados - ascendente - descendente

-Estructura deseada:
One page. La barra debe acompañar el “scrolleo”. Filtro tags debería contar con una búsqueda inteligente.

**Comment by mechafiz** [comment]
Estado: UX
